# Site settings
title: Alex Kshutashvili
email: alex.kshutashvili@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dominik Moritz: PhD student in Computer
  Science & Engineering at the University of Washington.
  Interested in Data Visualization and Databases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kshutashvili.github.io" # the base hostname & protocol for your site
production_url: "https://kshutashvili.github.io"
github_username: domoritz
permalink: /blog/:year/:month/:title.html

twitter:
  username: domoritz

# Google Analytics
google_analytics_tracking_id: UA-3992453-11

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
